source 'https://rubygems.org'
ruby '1.9.3'

gem 'rails', '4.0.2'
gem 'bcrypt-ruby', '3.1.2'
gem 'will_paginate', '3.0.4'
gem 'faker', '1.1.2'

gem 'modernizr-rails'
gem 'sass-rails', '>= 3.2' # sass-rails needs to be higher than 3.2
gem 'bootstrap-sass', '~> 3.1.1'
gem "compass-rails"

gem 'uglifier', '2.1.1'
gem 'coffee-rails', '4.0.1'
gem 'jquery-rails', '3.0.4'
gem 'turbolinks', '1.1.1'
gem 'jbuilder', '1.0.2'
gem 'pg', '0.15.1'

gem "flickraw", "0.9.7"
gem 'omniauth'
gem 'omniauth-facebook', '1.4.0'
gem 'omniauth-google-oauth2'

gem 'execjs'
gem 'therubyracer'

gem 'youtube_it'
gem 'inherited_resources'

group :doc do
  gem 'sdoc', '0.3.20', require: false
end

group :production do
#  gem 'pg', '0.15.1'
  gem 'rails_12factor', '0.0.2'
end